title: RPG Campaign Summaries
markdown: kramdown
exclude: [build_site.sh, source, README.md, CNAME]

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "es"
    values:
      lang: es
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "es/pirates-of-drinax"
    values:
      theme: sci-fi
  - scope:
      path: "en/pirates-of-drinax"
    values:
      theme: sci-fi
  - scope:
      path: "es/ravenloft"
    values:
      theme: gothic
  - scope:
      path: "en/ravenloft"
    values:
      theme: gothic
