title: RPG Campaign Summaries
markdown: kramdown
exclude: [build_site.sh, source, README.md, CNAME]

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "es"
    values:
      lang: es
  - scope:
      path: "en"
    values:
      lang: en
